/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarHashRouteImport } from './routes/validar.$hash'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app/usuarios'
import { Route as AuthenticatedAppProfissionaisRouteImport } from './routes/_authenticated/app/profissionais'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app/financeiro'
import { Route as AuthenticatedAppDashboardClinicoRouteImport } from './routes/_authenticated/app/dashboard-clinico'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app/configuracoes'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAppPacientesIndexRouteImport } from './routes/_authenticated/app/pacientes/index'
import { Route as AuthenticatedAppPacientesIdRouteImport } from './routes/_authenticated/app/pacientes/$id'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarHashRoute = ValidarHashRouteImport.update({
  id: '/validar/$hash',
  path: '/validar/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/app/usuarios',
    path: '/app/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfissionaisRoute =
  AuthenticatedAppProfissionaisRouteImport.update({
    id: '/app/profissionais',
    path: '/app/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/app/financeiro',
    path: '/app/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDashboardClinicoRoute =
  AuthenticatedAppDashboardClinicoRouteImport.update({
    id: '/app/dashboard-clinico',
    path: '/app/dashboard-clinico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/app/configuracoes',
    path: '/app/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPacientesIndexRoute =
  AuthenticatedAppPacientesIndexRouteImport.update({
    id: '/app/pacientes/',
    path: '/app/pacientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPacientesIdRoute =
  AuthenticatedAppPacientesIdRouteImport.update({
    id: '/app/pacientes/$id',
    path: '/app/pacientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/_authenticated/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/validar/$hash'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/financeiro'
    | '/app/profissionais'
    | '/app/usuarios'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/validar/$hash'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/financeiro'
    | '/app/profissionais'
    | '/app/usuarios'
    | '/app'
    | '/app/pacientes/$id'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/validar/$hash'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/dashboard-clinico'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/profissionais'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/pacientes/$id'
    | '/_authenticated/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ValidarHashRoute: typeof ValidarHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$hash': {
      id: '/validar/$hash'
      path: '/validar/$hash'
      fullPath: '/validar/$hash'
      preLoaderRoute: typeof ValidarHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/app/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profissionais': {
      id: '/_authenticated/app/profissionais'
      path: '/app/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AuthenticatedAppProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/app/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard-clinico': {
      id: '/_authenticated/app/dashboard-clinico'
      path: '/app/dashboard-clinico'
      fullPath: '/app/dashboard-clinico'
      preLoaderRoute: typeof AuthenticatedAppDashboardClinicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pacientes/': {
      id: '/_authenticated/app/pacientes/'
      path: '/app/pacientes'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AuthenticatedAppPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pacientes/$id': {
      id: '/_authenticated/app/pacientes/$id'
      path: '/app/pacientes/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedAppPacientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDashboardClinicoRoute: typeof AuthenticatedAppDashboardClinicoRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppProfissionaisRoute: typeof AuthenticatedAppProfissionaisRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPacientesIdRoute: typeof AuthenticatedAppPacientesIdRoute
  AuthenticatedAppPacientesIndexRoute: typeof AuthenticatedAppPacientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDashboardClinicoRoute: AuthenticatedAppDashboardClinicoRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppProfissionaisRoute: AuthenticatedAppProfissionaisRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPacientesIdRoute: AuthenticatedAppPacientesIdRoute,
  AuthenticatedAppPacientesIndexRoute: AuthenticatedAppPacientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
  ValidarHashRoute: ValidarHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
