/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarHashRouteImport } from './routes/validar.$hash'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app/usuarios'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app/templates'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app/relatorios'
import { Route as AuthenticatedAppRecibosRouteImport } from './routes/_authenticated/app/recibos'
import { Route as AuthenticatedAppReavaliacoesRouteImport } from './routes/_authenticated/app/reavaliacoes'
import { Route as AuthenticatedAppProfissionaisRouteImport } from './routes/_authenticated/app/profissionais'
import { Route as AuthenticatedAppMarketingRouteImport } from './routes/_authenticated/app/marketing'
import { Route as AuthenticatedAppHomeCareRouteImport } from './routes/_authenticated/app/home-care'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app/financeiro'
import { Route as AuthenticatedAppEvolucoesRouteImport } from './routes/_authenticated/app/evolucoes'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app/documentos'
import { Route as AuthenticatedAppDiferenciaisRouteImport } from './routes/_authenticated/app/diferenciais'
import { Route as AuthenticatedAppDashboardClinicoRouteImport } from './routes/_authenticated/app/dashboard-clinico'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app/configuracoes'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated/app/biblioteca'
import { Route as AuthenticatedAppAvaliacoesRouteImport } from './routes/_authenticated/app/avaliacoes'
import { Route as AuthenticatedAppAltasRouteImport } from './routes/_authenticated/app/altas'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAppAdminSaasRouteImport } from './routes/_authenticated/app/admin-saas'
import { Route as AuthenticatedAppPacientesIndexRouteImport } from './routes/_authenticated/app/pacientes/index'
import { Route as AuthenticatedAppPacientesIdRouteImport } from './routes/_authenticated/app/pacientes/$id'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarHashRoute = ValidarHashRouteImport.update({
  id: '/validar/$hash',
  path: '/validar/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRecibosRoute = AuthenticatedAppRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReavaliacoesRoute =
  AuthenticatedAppReavaliacoesRouteImport.update({
    id: '/reavaliacoes',
    path: '/reavaliacoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProfissionaisRoute =
  AuthenticatedAppProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMarketingRoute =
  AuthenticatedAppMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHomeCareRoute =
  AuthenticatedAppHomeCareRouteImport.update({
    id: '/home-care',
    path: '/home-care',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEvolucoesRoute =
  AuthenticatedAppEvolucoesRouteImport.update({
    id: '/evolucoes',
    path: '/evolucoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDiferenciaisRoute =
  AuthenticatedAppDiferenciaisRouteImport.update({
    id: '/diferenciais',
    path: '/diferenciais',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardClinicoRoute =
  AuthenticatedAppDashboardClinicoRouteImport.update({
    id: '/dashboard-clinico',
    path: '/dashboard-clinico',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAvaliacoesRoute =
  AuthenticatedAppAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAltasRoute = AuthenticatedAppAltasRouteImport.update({
  id: '/altas',
  path: '/altas',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAdminSaasRoute =
  AuthenticatedAppAdminSaasRouteImport.update({
    id: '/admin-saas',
    path: '/admin-saas',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPacientesIndexRoute =
  AuthenticatedAppPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPacientesIdRoute =
  AuthenticatedAppPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/validar/$hash': typeof ValidarHashRoute
  '/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/altas': typeof AuthenticatedAppAltasRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/altas': typeof AuthenticatedAppAltasRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/validar/$hash': typeof ValidarHashRoute
  '/_authenticated/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/altas': typeof AuthenticatedAppAltasRoute
  '/_authenticated/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/_authenticated/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/_authenticated/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/_authenticated/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/_authenticated/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/_authenticated/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/_authenticated/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/_authenticated/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/app'
    | '/validar/$hash'
    | '/app/admin-saas'
    | '/app/agenda'
    | '/app/altas'
    | '/app/avaliacoes'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/diferenciais'
    | '/app/documentos'
    | '/app/evolucoes'
    | '/app/financeiro'
    | '/app/home-care'
    | '/app/marketing'
    | '/app/profissionais'
    | '/app/reavaliacoes'
    | '/app/recibos'
    | '/app/relatorios'
    | '/app/templates'
    | '/app/usuarios'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/validar/$hash'
    | '/app/admin-saas'
    | '/app/agenda'
    | '/app/altas'
    | '/app/avaliacoes'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/diferenciais'
    | '/app/documentos'
    | '/app/evolucoes'
    | '/app/financeiro'
    | '/app/home-care'
    | '/app/marketing'
    | '/app/profissionais'
    | '/app/reavaliacoes'
    | '/app/recibos'
    | '/app/relatorios'
    | '/app/templates'
    | '/app/usuarios'
    | '/app'
    | '/app/pacientes/$id'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/_authenticated/app'
    | '/validar/$hash'
    | '/_authenticated/app/admin-saas'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/altas'
    | '/_authenticated/app/avaliacoes'
    | '/_authenticated/app/biblioteca'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/dashboard-clinico'
    | '/_authenticated/app/diferenciais'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/evolucoes'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/home-care'
    | '/_authenticated/app/marketing'
    | '/_authenticated/app/profissionais'
    | '/_authenticated/app/reavaliacoes'
    | '/_authenticated/app/recibos'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/pacientes/$id'
    | '/_authenticated/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ValidarHashRoute: typeof ValidarHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$hash': {
      id: '/validar/$hash'
      path: '/validar/$hash'
      fullPath: '/validar/$hash'
      preLoaderRoute: typeof ValidarHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/recibos': {
      id: '/_authenticated/app/recibos'
      path: '/recibos'
      fullPath: '/app/recibos'
      preLoaderRoute: typeof AuthenticatedAppRecibosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reavaliacoes': {
      id: '/_authenticated/app/reavaliacoes'
      path: '/reavaliacoes'
      fullPath: '/app/reavaliacoes'
      preLoaderRoute: typeof AuthenticatedAppReavaliacoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/profissionais': {
      id: '/_authenticated/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AuthenticatedAppProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/marketing': {
      id: '/_authenticated/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AuthenticatedAppMarketingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/home-care': {
      id: '/_authenticated/app/home-care'
      path: '/home-care'
      fullPath: '/app/home-care'
      preLoaderRoute: typeof AuthenticatedAppHomeCareRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/evolucoes': {
      id: '/_authenticated/app/evolucoes'
      path: '/evolucoes'
      fullPath: '/app/evolucoes'
      preLoaderRoute: typeof AuthenticatedAppEvolucoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/diferenciais': {
      id: '/_authenticated/app/diferenciais'
      path: '/diferenciais'
      fullPath: '/app/diferenciais'
      preLoaderRoute: typeof AuthenticatedAppDiferenciaisRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard-clinico': {
      id: '/_authenticated/app/dashboard-clinico'
      path: '/dashboard-clinico'
      fullPath: '/app/dashboard-clinico'
      preLoaderRoute: typeof AuthenticatedAppDashboardClinicoRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/biblioteca': {
      id: '/_authenticated/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/avaliacoes': {
      id: '/_authenticated/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAppAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/altas': {
      id: '/_authenticated/app/altas'
      path: '/altas'
      fullPath: '/app/altas'
      preLoaderRoute: typeof AuthenticatedAppAltasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin-saas': {
      id: '/_authenticated/app/admin-saas'
      path: '/admin-saas'
      fullPath: '/app/admin-saas'
      preLoaderRoute: typeof AuthenticatedAppAdminSaasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/pacientes/': {
      id: '/_authenticated/app/pacientes/'
      path: '/pacientes'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AuthenticatedAppPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/pacientes/$id': {
      id: '/_authenticated/app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedAppPacientesIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAdminSaasRoute: typeof AuthenticatedAppAdminSaasRoute
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAltasRoute: typeof AuthenticatedAppAltasRoute
  AuthenticatedAppAvaliacoesRoute: typeof AuthenticatedAppAvaliacoesRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDashboardClinicoRoute: typeof AuthenticatedAppDashboardClinicoRoute
  AuthenticatedAppDiferenciaisRoute: typeof AuthenticatedAppDiferenciaisRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppEvolucoesRoute: typeof AuthenticatedAppEvolucoesRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppHomeCareRoute: typeof AuthenticatedAppHomeCareRoute
  AuthenticatedAppMarketingRoute: typeof AuthenticatedAppMarketingRoute
  AuthenticatedAppProfissionaisRoute: typeof AuthenticatedAppProfissionaisRoute
  AuthenticatedAppReavaliacoesRoute: typeof AuthenticatedAppReavaliacoesRoute
  AuthenticatedAppRecibosRoute: typeof AuthenticatedAppRecibosRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPacientesIdRoute: typeof AuthenticatedAppPacientesIdRoute
  AuthenticatedAppPacientesIndexRoute: typeof AuthenticatedAppPacientesIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAdminSaasRoute: AuthenticatedAppAdminSaasRoute,
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAltasRoute: AuthenticatedAppAltasRoute,
  AuthenticatedAppAvaliacoesRoute: AuthenticatedAppAvaliacoesRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDashboardClinicoRoute: AuthenticatedAppDashboardClinicoRoute,
  AuthenticatedAppDiferenciaisRoute: AuthenticatedAppDiferenciaisRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppEvolucoesRoute: AuthenticatedAppEvolucoesRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppHomeCareRoute: AuthenticatedAppHomeCareRoute,
  AuthenticatedAppMarketingRoute: AuthenticatedAppMarketingRoute,
  AuthenticatedAppProfissionaisRoute: AuthenticatedAppProfissionaisRoute,
  AuthenticatedAppReavaliacoesRoute: AuthenticatedAppReavaliacoesRoute,
  AuthenticatedAppRecibosRoute: AuthenticatedAppRecibosRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPacientesIdRoute: AuthenticatedAppPacientesIdRoute,
  AuthenticatedAppPacientesIndexRoute: AuthenticatedAppPacientesIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
  ValidarHashRoute: ValidarHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
