/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarHashRouteImport } from './routes/validar.$hash'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app/usuarios'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app/templates'
import { Route as AuthenticatedAppSemClinicaRouteImport } from './routes/_authenticated/app/sem-clinica'
import { Route as AuthenticatedAppSelecionarClinicaRouteImport } from './routes/_authenticated/app/selecionar-clinica'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app/relatorios'
import { Route as AuthenticatedAppRecibosRouteImport } from './routes/_authenticated/app/recibos'
import { Route as AuthenticatedAppReavaliacoesRouteImport } from './routes/_authenticated/app/reavaliacoes'
import { Route as AuthenticatedAppProfissionaisRouteImport } from './routes/_authenticated/app/profissionais'
import { Route as AuthenticatedAppMarketingRouteImport } from './routes/_authenticated/app/marketing'
import { Route as AuthenticatedAppHomeCareRouteImport } from './routes/_authenticated/app/home-care'
import { Route as AuthenticatedAppEvolucoesRouteImport } from './routes/_authenticated/app/evolucoes'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app/documentos'
import { Route as AuthenticatedAppDiferenciaisRouteImport } from './routes/_authenticated/app/diferenciais'
import { Route as AuthenticatedAppDashboardClinicoRouteImport } from './routes/_authenticated/app/dashboard-clinico'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app/configuracoes'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated/app/biblioteca'
import { Route as AuthenticatedAppAvaliacoesRouteImport } from './routes/_authenticated/app/avaliacoes'
import { Route as AuthenticatedAppAltasRouteImport } from './routes/_authenticated/app/altas'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAppAdminSaasRouteImport } from './routes/_authenticated/app/admin-saas'
import { Route as AuthenticatedAppPacientesIndexRouteImport } from './routes/_authenticated/app/pacientes/index'
import { Route as AuthenticatedAppFinanceiroIndexRouteImport } from './routes/_authenticated/app/financeiro/index'
import { Route as AuthenticatedAppPacientesIdRouteImport } from './routes/_authenticated/app/pacientes/$id'
import { Route as AuthenticatedAppFinanceiroRecibosRouteImport } from './routes/_authenticated/app/financeiro/recibos'
import { Route as AuthenticatedAppFinanceiroReceitaProfissionalRouteImport } from './routes/_authenticated/app/financeiro/receita-profissional'
import { Route as AuthenticatedAppFinanceiroReceberRouteImport } from './routes/_authenticated/app/financeiro/receber'
import { Route as AuthenticatedAppFinanceiroPagarRouteImport } from './routes/_authenticated/app/financeiro/pagar'
import { Route as AuthenticatedAppFinanceiroPacotesRouteImport } from './routes/_authenticated/app/financeiro/pacotes'
import { Route as AuthenticatedAppFinanceiroInadimplenciaRouteImport } from './routes/_authenticated/app/financeiro/inadimplencia'
import { Route as AuthenticatedAppFinanceiroFluxoRouteImport } from './routes/_authenticated/app/financeiro/fluxo'
import { Route as AuthenticatedAppFinanceiroConveniosRouteImport } from './routes/_authenticated/app/financeiro/convenios'
import { Route as AuthenticatedAppFinanceiroAdministracaoRouteImport } from './routes/_authenticated/app/financeiro/administracao'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarHashRoute = ValidarHashRouteImport.update({
  id: '/validar/$hash',
  path: '/validar/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSemClinicaRoute =
  AuthenticatedAppSemClinicaRouteImport.update({
    id: '/sem-clinica',
    path: '/sem-clinica',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSelecionarClinicaRoute =
  AuthenticatedAppSelecionarClinicaRouteImport.update({
    id: '/selecionar-clinica',
    path: '/selecionar-clinica',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRecibosRoute = AuthenticatedAppRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReavaliacoesRoute =
  AuthenticatedAppReavaliacoesRouteImport.update({
    id: '/reavaliacoes',
    path: '/reavaliacoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProfissionaisRoute =
  AuthenticatedAppProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMarketingRoute =
  AuthenticatedAppMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHomeCareRoute =
  AuthenticatedAppHomeCareRouteImport.update({
    id: '/home-care',
    path: '/home-care',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEvolucoesRoute =
  AuthenticatedAppEvolucoesRouteImport.update({
    id: '/evolucoes',
    path: '/evolucoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDiferenciaisRoute =
  AuthenticatedAppDiferenciaisRouteImport.update({
    id: '/diferenciais',
    path: '/diferenciais',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardClinicoRoute =
  AuthenticatedAppDashboardClinicoRouteImport.update({
    id: '/dashboard-clinico',
    path: '/dashboard-clinico',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAvaliacoesRoute =
  AuthenticatedAppAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAltasRoute = AuthenticatedAppAltasRouteImport.update({
  id: '/altas',
  path: '/altas',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAdminSaasRoute =
  AuthenticatedAppAdminSaasRouteImport.update({
    id: '/admin-saas',
    path: '/admin-saas',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPacientesIndexRoute =
  AuthenticatedAppPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroIndexRoute =
  AuthenticatedAppFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPacientesIdRoute =
  AuthenticatedAppPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroRecibosRoute =
  AuthenticatedAppFinanceiroRecibosRouteImport.update({
    id: '/financeiro/recibos',
    path: '/financeiro/recibos',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroReceitaProfissionalRoute =
  AuthenticatedAppFinanceiroReceitaProfissionalRouteImport.update({
    id: '/financeiro/receita-profissional',
    path: '/financeiro/receita-profissional',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroReceberRoute =
  AuthenticatedAppFinanceiroReceberRouteImport.update({
    id: '/financeiro/receber',
    path: '/financeiro/receber',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroPagarRoute =
  AuthenticatedAppFinanceiroPagarRouteImport.update({
    id: '/financeiro/pagar',
    path: '/financeiro/pagar',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroPacotesRoute =
  AuthenticatedAppFinanceiroPacotesRouteImport.update({
    id: '/financeiro/pacotes',
    path: '/financeiro/pacotes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroInadimplenciaRoute =
  AuthenticatedAppFinanceiroInadimplenciaRouteImport.update({
    id: '/financeiro/inadimplencia',
    path: '/financeiro/inadimplencia',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroFluxoRoute =
  AuthenticatedAppFinanceiroFluxoRouteImport.update({
    id: '/financeiro/fluxo',
    path: '/financeiro/fluxo',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroConveniosRoute =
  AuthenticatedAppFinanceiroConveniosRouteImport.update({
    id: '/financeiro/convenios',
    path: '/financeiro/convenios',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroAdministracaoRoute =
  AuthenticatedAppFinanceiroAdministracaoRouteImport.update({
    id: '/financeiro/administracao',
    path: '/financeiro/administracao',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/validar/$hash': typeof ValidarHashRoute
  '/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/altas': typeof AuthenticatedAppAltasRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/selecionar-clinica': typeof AuthenticatedAppSelecionarClinicaRoute
  '/app/sem-clinica': typeof AuthenticatedAppSemClinicaRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/administracao': typeof AuthenticatedAppFinanceiroAdministracaoRoute
  '/app/financeiro/convenios': typeof AuthenticatedAppFinanceiroConveniosRoute
  '/app/financeiro/fluxo': typeof AuthenticatedAppFinanceiroFluxoRoute
  '/app/financeiro/inadimplencia': typeof AuthenticatedAppFinanceiroInadimplenciaRoute
  '/app/financeiro/pacotes': typeof AuthenticatedAppFinanceiroPacotesRoute
  '/app/financeiro/pagar': typeof AuthenticatedAppFinanceiroPagarRoute
  '/app/financeiro/receber': typeof AuthenticatedAppFinanceiroReceberRoute
  '/app/financeiro/receita-profissional': typeof AuthenticatedAppFinanceiroReceitaProfissionalRoute
  '/app/financeiro/recibos': typeof AuthenticatedAppFinanceiroRecibosRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
  '/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/altas': typeof AuthenticatedAppAltasRoute
  '/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/selecionar-clinica': typeof AuthenticatedAppSelecionarClinicaRoute
  '/app/sem-clinica': typeof AuthenticatedAppSemClinicaRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/administracao': typeof AuthenticatedAppFinanceiroAdministracaoRoute
  '/app/financeiro/convenios': typeof AuthenticatedAppFinanceiroConveniosRoute
  '/app/financeiro/fluxo': typeof AuthenticatedAppFinanceiroFluxoRoute
  '/app/financeiro/inadimplencia': typeof AuthenticatedAppFinanceiroInadimplenciaRoute
  '/app/financeiro/pacotes': typeof AuthenticatedAppFinanceiroPacotesRoute
  '/app/financeiro/pagar': typeof AuthenticatedAppFinanceiroPagarRoute
  '/app/financeiro/receber': typeof AuthenticatedAppFinanceiroReceberRoute
  '/app/financeiro/receita-profissional': typeof AuthenticatedAppFinanceiroReceitaProfissionalRoute
  '/app/financeiro/recibos': typeof AuthenticatedAppFinanceiroRecibosRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroIndexRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/validar/$hash': typeof ValidarHashRoute
  '/_authenticated/app/admin-saas': typeof AuthenticatedAppAdminSaasRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/altas': typeof AuthenticatedAppAltasRoute
  '/_authenticated/app/avaliacoes': typeof AuthenticatedAppAvaliacoesRoute
  '/_authenticated/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/dashboard-clinico': typeof AuthenticatedAppDashboardClinicoRoute
  '/_authenticated/app/diferenciais': typeof AuthenticatedAppDiferenciaisRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/evolucoes': typeof AuthenticatedAppEvolucoesRoute
  '/_authenticated/app/home-care': typeof AuthenticatedAppHomeCareRoute
  '/_authenticated/app/marketing': typeof AuthenticatedAppMarketingRoute
  '/_authenticated/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/_authenticated/app/reavaliacoes': typeof AuthenticatedAppReavaliacoesRoute
  '/_authenticated/app/recibos': typeof AuthenticatedAppRecibosRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/selecionar-clinica': typeof AuthenticatedAppSelecionarClinicaRoute
  '/_authenticated/app/sem-clinica': typeof AuthenticatedAppSemClinicaRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/financeiro/administracao': typeof AuthenticatedAppFinanceiroAdministracaoRoute
  '/_authenticated/app/financeiro/convenios': typeof AuthenticatedAppFinanceiroConveniosRoute
  '/_authenticated/app/financeiro/fluxo': typeof AuthenticatedAppFinanceiroFluxoRoute
  '/_authenticated/app/financeiro/inadimplencia': typeof AuthenticatedAppFinanceiroInadimplenciaRoute
  '/_authenticated/app/financeiro/pacotes': typeof AuthenticatedAppFinanceiroPacotesRoute
  '/_authenticated/app/financeiro/pagar': typeof AuthenticatedAppFinanceiroPagarRoute
  '/_authenticated/app/financeiro/receber': typeof AuthenticatedAppFinanceiroReceberRoute
  '/_authenticated/app/financeiro/receita-profissional': typeof AuthenticatedAppFinanceiroReceitaProfissionalRoute
  '/_authenticated/app/financeiro/recibos': typeof AuthenticatedAppFinanceiroRecibosRoute
  '/_authenticated/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/_authenticated/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
  '/_authenticated/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/set-password'
    | '/app'
    | '/validar/$hash'
    | '/app/admin-saas'
    | '/app/agenda'
    | '/app/altas'
    | '/app/avaliacoes'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/diferenciais'
    | '/app/documentos'
    | '/app/evolucoes'
    | '/app/home-care'
    | '/app/marketing'
    | '/app/profissionais'
    | '/app/reavaliacoes'
    | '/app/recibos'
    | '/app/relatorios'
    | '/app/selecionar-clinica'
    | '/app/sem-clinica'
    | '/app/templates'
    | '/app/usuarios'
    | '/app/'
    | '/app/financeiro/administracao'
    | '/app/financeiro/convenios'
    | '/app/financeiro/fluxo'
    | '/app/financeiro/inadimplencia'
    | '/app/financeiro/pacotes'
    | '/app/financeiro/pagar'
    | '/app/financeiro/receber'
    | '/app/financeiro/receita-profissional'
    | '/app/financeiro/recibos'
    | '/app/pacientes/$id'
    | '/app/financeiro/'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/set-password'
    | '/validar/$hash'
    | '/app/admin-saas'
    | '/app/agenda'
    | '/app/altas'
    | '/app/avaliacoes'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/dashboard-clinico'
    | '/app/diferenciais'
    | '/app/documentos'
    | '/app/evolucoes'
    | '/app/home-care'
    | '/app/marketing'
    | '/app/profissionais'
    | '/app/reavaliacoes'
    | '/app/recibos'
    | '/app/relatorios'
    | '/app/selecionar-clinica'
    | '/app/sem-clinica'
    | '/app/templates'
    | '/app/usuarios'
    | '/app'
    | '/app/financeiro/administracao'
    | '/app/financeiro/convenios'
    | '/app/financeiro/fluxo'
    | '/app/financeiro/inadimplencia'
    | '/app/financeiro/pacotes'
    | '/app/financeiro/pagar'
    | '/app/financeiro/receber'
    | '/app/financeiro/receita-profissional'
    | '/app/financeiro/recibos'
    | '/app/pacientes/$id'
    | '/app/financeiro'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/set-password'
    | '/_authenticated/app'
    | '/validar/$hash'
    | '/_authenticated/app/admin-saas'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/altas'
    | '/_authenticated/app/avaliacoes'
    | '/_authenticated/app/biblioteca'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/dashboard-clinico'
    | '/_authenticated/app/diferenciais'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/evolucoes'
    | '/_authenticated/app/home-care'
    | '/_authenticated/app/marketing'
    | '/_authenticated/app/profissionais'
    | '/_authenticated/app/reavaliacoes'
    | '/_authenticated/app/recibos'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/selecionar-clinica'
    | '/_authenticated/app/sem-clinica'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/financeiro/administracao'
    | '/_authenticated/app/financeiro/convenios'
    | '/_authenticated/app/financeiro/fluxo'
    | '/_authenticated/app/financeiro/inadimplencia'
    | '/_authenticated/app/financeiro/pacotes'
    | '/_authenticated/app/financeiro/pagar'
    | '/_authenticated/app/financeiro/receber'
    | '/_authenticated/app/financeiro/receita-profissional'
    | '/_authenticated/app/financeiro/recibos'
    | '/_authenticated/app/pacientes/$id'
    | '/_authenticated/app/financeiro/'
    | '/_authenticated/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ValidarHashRoute: typeof ValidarHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$hash': {
      id: '/validar/$hash'
      path: '/validar/$hash'
      fullPath: '/validar/$hash'
      preLoaderRoute: typeof ValidarHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/sem-clinica': {
      id: '/_authenticated/app/sem-clinica'
      path: '/sem-clinica'
      fullPath: '/app/sem-clinica'
      preLoaderRoute: typeof AuthenticatedAppSemClinicaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/selecionar-clinica': {
      id: '/_authenticated/app/selecionar-clinica'
      path: '/selecionar-clinica'
      fullPath: '/app/selecionar-clinica'
      preLoaderRoute: typeof AuthenticatedAppSelecionarClinicaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/recibos': {
      id: '/_authenticated/app/recibos'
      path: '/recibos'
      fullPath: '/app/recibos'
      preLoaderRoute: typeof AuthenticatedAppRecibosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reavaliacoes': {
      id: '/_authenticated/app/reavaliacoes'
      path: '/reavaliacoes'
      fullPath: '/app/reavaliacoes'
      preLoaderRoute: typeof AuthenticatedAppReavaliacoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/profissionais': {
      id: '/_authenticated/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AuthenticatedAppProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/marketing': {
      id: '/_authenticated/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AuthenticatedAppMarketingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/home-care': {
      id: '/_authenticated/app/home-care'
      path: '/home-care'
      fullPath: '/app/home-care'
      preLoaderRoute: typeof AuthenticatedAppHomeCareRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/evolucoes': {
      id: '/_authenticated/app/evolucoes'
      path: '/evolucoes'
      fullPath: '/app/evolucoes'
      preLoaderRoute: typeof AuthenticatedAppEvolucoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/diferenciais': {
      id: '/_authenticated/app/diferenciais'
      path: '/diferenciais'
      fullPath: '/app/diferenciais'
      preLoaderRoute: typeof AuthenticatedAppDiferenciaisRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard-clinico': {
      id: '/_authenticated/app/dashboard-clinico'
      path: '/dashboard-clinico'
      fullPath: '/app/dashboard-clinico'
      preLoaderRoute: typeof AuthenticatedAppDashboardClinicoRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/biblioteca': {
      id: '/_authenticated/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/avaliacoes': {
      id: '/_authenticated/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAppAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/altas': {
      id: '/_authenticated/app/altas'
      path: '/altas'
      fullPath: '/app/altas'
      preLoaderRoute: typeof AuthenticatedAppAltasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin-saas': {
      id: '/_authenticated/app/admin-saas'
      path: '/admin-saas'
      fullPath: '/app/admin-saas'
      preLoaderRoute: typeof AuthenticatedAppAdminSaasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/pacientes/': {
      id: '/_authenticated/app/pacientes/'
      path: '/pacientes'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AuthenticatedAppPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/': {
      id: '/_authenticated/app/financeiro/'
      path: '/financeiro'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/pacientes/$id': {
      id: '/_authenticated/app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedAppPacientesIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/recibos': {
      id: '/_authenticated/app/financeiro/recibos'
      path: '/financeiro/recibos'
      fullPath: '/app/financeiro/recibos'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRecibosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/receita-profissional': {
      id: '/_authenticated/app/financeiro/receita-profissional'
      path: '/financeiro/receita-profissional'
      fullPath: '/app/financeiro/receita-profissional'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroReceitaProfissionalRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/receber': {
      id: '/_authenticated/app/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/app/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/pagar': {
      id: '/_authenticated/app/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/app/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/pacotes': {
      id: '/_authenticated/app/financeiro/pacotes'
      path: '/financeiro/pacotes'
      fullPath: '/app/financeiro/pacotes'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroPacotesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/inadimplencia': {
      id: '/_authenticated/app/financeiro/inadimplencia'
      path: '/financeiro/inadimplencia'
      fullPath: '/app/financeiro/inadimplencia'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroInadimplenciaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/fluxo': {
      id: '/_authenticated/app/financeiro/fluxo'
      path: '/financeiro/fluxo'
      fullPath: '/app/financeiro/fluxo'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroFluxoRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/convenios': {
      id: '/_authenticated/app/financeiro/convenios'
      path: '/financeiro/convenios'
      fullPath: '/app/financeiro/convenios'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroConveniosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/financeiro/administracao': {
      id: '/_authenticated/app/financeiro/administracao'
      path: '/financeiro/administracao'
      fullPath: '/app/financeiro/administracao'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroAdministracaoRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAdminSaasRoute: typeof AuthenticatedAppAdminSaasRoute
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAltasRoute: typeof AuthenticatedAppAltasRoute
  AuthenticatedAppAvaliacoesRoute: typeof AuthenticatedAppAvaliacoesRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDashboardClinicoRoute: typeof AuthenticatedAppDashboardClinicoRoute
  AuthenticatedAppDiferenciaisRoute: typeof AuthenticatedAppDiferenciaisRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppEvolucoesRoute: typeof AuthenticatedAppEvolucoesRoute
  AuthenticatedAppHomeCareRoute: typeof AuthenticatedAppHomeCareRoute
  AuthenticatedAppMarketingRoute: typeof AuthenticatedAppMarketingRoute
  AuthenticatedAppProfissionaisRoute: typeof AuthenticatedAppProfissionaisRoute
  AuthenticatedAppReavaliacoesRoute: typeof AuthenticatedAppReavaliacoesRoute
  AuthenticatedAppRecibosRoute: typeof AuthenticatedAppRecibosRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppSelecionarClinicaRoute: typeof AuthenticatedAppSelecionarClinicaRoute
  AuthenticatedAppSemClinicaRoute: typeof AuthenticatedAppSemClinicaRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFinanceiroAdministracaoRoute: typeof AuthenticatedAppFinanceiroAdministracaoRoute
  AuthenticatedAppFinanceiroConveniosRoute: typeof AuthenticatedAppFinanceiroConveniosRoute
  AuthenticatedAppFinanceiroFluxoRoute: typeof AuthenticatedAppFinanceiroFluxoRoute
  AuthenticatedAppFinanceiroInadimplenciaRoute: typeof AuthenticatedAppFinanceiroInadimplenciaRoute
  AuthenticatedAppFinanceiroPacotesRoute: typeof AuthenticatedAppFinanceiroPacotesRoute
  AuthenticatedAppFinanceiroPagarRoute: typeof AuthenticatedAppFinanceiroPagarRoute
  AuthenticatedAppFinanceiroReceberRoute: typeof AuthenticatedAppFinanceiroReceberRoute
  AuthenticatedAppFinanceiroReceitaProfissionalRoute: typeof AuthenticatedAppFinanceiroReceitaProfissionalRoute
  AuthenticatedAppFinanceiroRecibosRoute: typeof AuthenticatedAppFinanceiroRecibosRoute
  AuthenticatedAppPacientesIdRoute: typeof AuthenticatedAppPacientesIdRoute
  AuthenticatedAppFinanceiroIndexRoute: typeof AuthenticatedAppFinanceiroIndexRoute
  AuthenticatedAppPacientesIndexRoute: typeof AuthenticatedAppPacientesIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAdminSaasRoute: AuthenticatedAppAdminSaasRoute,
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAltasRoute: AuthenticatedAppAltasRoute,
  AuthenticatedAppAvaliacoesRoute: AuthenticatedAppAvaliacoesRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDashboardClinicoRoute: AuthenticatedAppDashboardClinicoRoute,
  AuthenticatedAppDiferenciaisRoute: AuthenticatedAppDiferenciaisRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppEvolucoesRoute: AuthenticatedAppEvolucoesRoute,
  AuthenticatedAppHomeCareRoute: AuthenticatedAppHomeCareRoute,
  AuthenticatedAppMarketingRoute: AuthenticatedAppMarketingRoute,
  AuthenticatedAppProfissionaisRoute: AuthenticatedAppProfissionaisRoute,
  AuthenticatedAppReavaliacoesRoute: AuthenticatedAppReavaliacoesRoute,
  AuthenticatedAppRecibosRoute: AuthenticatedAppRecibosRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppSelecionarClinicaRoute:
    AuthenticatedAppSelecionarClinicaRoute,
  AuthenticatedAppSemClinicaRoute: AuthenticatedAppSemClinicaRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFinanceiroAdministracaoRoute:
    AuthenticatedAppFinanceiroAdministracaoRoute,
  AuthenticatedAppFinanceiroConveniosRoute:
    AuthenticatedAppFinanceiroConveniosRoute,
  AuthenticatedAppFinanceiroFluxoRoute: AuthenticatedAppFinanceiroFluxoRoute,
  AuthenticatedAppFinanceiroInadimplenciaRoute:
    AuthenticatedAppFinanceiroInadimplenciaRoute,
  AuthenticatedAppFinanceiroPacotesRoute:
    AuthenticatedAppFinanceiroPacotesRoute,
  AuthenticatedAppFinanceiroPagarRoute: AuthenticatedAppFinanceiroPagarRoute,
  AuthenticatedAppFinanceiroReceberRoute:
    AuthenticatedAppFinanceiroReceberRoute,
  AuthenticatedAppFinanceiroReceitaProfissionalRoute:
    AuthenticatedAppFinanceiroReceitaProfissionalRoute,
  AuthenticatedAppFinanceiroRecibosRoute:
    AuthenticatedAppFinanceiroRecibosRoute,
  AuthenticatedAppPacientesIdRoute: AuthenticatedAppPacientesIdRoute,
  AuthenticatedAppFinanceiroIndexRoute: AuthenticatedAppFinanceiroIndexRoute,
  AuthenticatedAppPacientesIndexRoute: AuthenticatedAppPacientesIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  ValidarHashRoute: ValidarHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
